output "module_outputs" {
  value     = <<EOD
    ======================================
      The following outputs were generated by this module:
    ======================================
    ======================================
                                    CREDENTIALS
    ======================================
    Username: "${var.admin_username}"
    Password: "${var.admin_password}"
    ======================================
                                    IP ADDRESSES
    ======================================    
    %{if !(lookup(local.config.WINDOWS_VIRTUAL_MACHINE, "domain_controller", null) == null)}
    Domain Controller IP: "${!(lookup(local.config.WINDOWS_VIRTUAL_MACHINE, "domain_controller", null) == null) ? module.windows_virtual_machine["domain_controller"].public_ip_address : null}"
    %{endif}
    %{if !(lookup(local.config.WINDOWS_VIRTUAL_MACHINE, "windows_server", null) == null)}
    Windows Server IP: "${!(lookup(local.config.WINDOWS_VIRTUAL_MACHINE, "windows_server", null) == null) ? module.windows_virtual_machine["windows_server"].public_ip_address : null}"
    %{endif}
    %{if !(lookup(local.config.WINDOWS_VIRTUAL_MACHINE, "windows_client", null) == null)}
    Windows Client IP: "${!(lookup(local.config.WINDOWS_VIRTUAL_MACHINE, "windows_client", null) == null) ? module.windows_virtual_machine["windows_client"].public_ip_address : null}"
    %{endif}
  EOD
  sensitive = true
}