---
# Terraform command variables
terraform_command:
  plan:
    name: plan
    state: planned
  apply:
    name: apply
    state: present
  destroy:
    name: destroy
    state: absent

# Terraform play variables
plan_file: '{{ playbook_dir }}/terraform.plan'
state_file: '{{ playbook_dir }}/terraform.tfstate'
lock_file: '{{ playbook_dir }}/.terraform.lock.hcl'
config_template: '{{ role_path }}/templates/config.yml.j2'
config: '{{ project_path }}/config/config.yaml'
inventory_file: '{{ playbook_dir }}/ansible/inventory/myazure_rm.yml'