name: Ansible Debugging

on:
  workflow_dispatch:

env:
  ANSIBLE_COLLECTIONS_PATHS: ${{ github.workspace }}/ansible/collections
  ANSIBLE_CONFIG_FILE: ${{ github.workspace }}/ansible/ansible.cfg

jobs:
  ansible_debugging:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - name: Login to Azure
        id: az_logon
        uses: azure/login@v1
        continue-on-error: true
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "subsciptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}""
            }   