name: Ansible Debugging

on:
  workflow_dispatch:

env:
  ANSIBLE_COLLECTIONS_PATHS: ${{ github.workspace }}/ansible/collections
  ANSIBLE_CONFIG_FILE: ${{ github.workspace }}/ansible/ansible.cfg

jobs:
  ansible_debugging:
    runs-on: ubuntu-latest


    steps:
      - id: checkout
        uses: actions/checkout@v3    
      - name: Setup Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: '3.10'
      - id: pip
        working-directory: ${{ github.workspace }}/ansible
        run: |
          pipx inject ansible-core pywinrm requests-ntlm
      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.6.1
        with:
          playbook: playbook.yml
          inventory: ./inventory/azure_rm.yml
          requirements: galaxy-requirements.yml
          directory: ${{ github.workspace }}/ansible
          options: |     
            -e admin_username=${{ secrets.ADMIN_USERNAME }}
            -e admin_password=${{ secrets.ADMIN_PASSWORD }}
            --verbose

      
