name: Ansible Debugging

on:
  push:

env:
  ANSIBLE_COLLECTIONS_PATHS: ${{ github.workspace }}/ansible/collections
  ANSIBLE_CONFIG_FILE: ${{ github.workspace }}/ansible/ansible.cfg

jobs:
  ansible_debugging:
    runs-on: ubuntu-latest
    env:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLOUD_ENVIRONMENT: "AzureCloud"

    steps:
      - id: checkout
        uses: actions/checkout@v3    
      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.6.1
        with:
          playbook: playbook.yml
          inventory: ./inventory/azure_rm.yml
          requirements: galaxy-requirements.yml
          directory: ${{ github.workspace }}/ansible
          options: |
            -e admin_username=${{ secrets.ADMIN_USERNAME }}
            -e admin_password=${{ secrets.ADMIN_PASSWORD }}
            --verbose

      
