name: Ansible Debugging

on:
  workflow_dispatch:

env:
  ANSIBLE_COLLECTIONS_PATHS: ${{ github.workspace }}/ansible/collections
  ANSIBLE_CONFIG_FILE: ${{ github.workspace }}/ansible/ansible.cfg

jobs:
  ansible_debugging:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - id: ansible
        working-directory: ${{ github.workspace }}/ansible
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}       
        run: |
          apt update \
          && apt -y install software-properties-common \
          && add-apt-repository --yes --update ppa:ansible/ansible \
          && apt -y install ansible python3-pip\
          && ansible-galaxy install -r requirements.yml \
          && curl -o https://github.com/ansible-collections/azure/blob/dev/requirements-azure.txt \
          && pip3 install -r requirements-azure.txt \
          && ansible-galaxy collection install azure.azcollection --force \
          && ansible-inventory -i inventory/myazure_rm.yml --list


#          source /opt/pipx/venvs/ansible-core/bin/activate \
#          && ansible-galaxy install -r requirements.yml \
#          && python -m pip install -r ./collections/ansible_collections/azure/azcollection/requirements-azure.txt \
#          && ansible-inventory -i inventory/myazure_rm.yml --list
#      - uses: dawidd6/action-ansible-playbook@v2.6.1
#        id: ansible
#        with:
#          playbook: playbook.yml
#          directory: ${{ github.workspace }}/ansible
#          options:
#            --verbose        
      